sachOnline/WebApplication1/Models/NHAXUATBAN.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHAXUATBAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHAXUATBAN()
        {
            this.SACHes = new HashSet<SACH>();
        }
    
        public int MaNXB { get; set; }
        public string TenNXB { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SACH> SACHes { get; set; }
    }
}

sachOnline/WebApplication1/Areas/Admin/Controllers/NhaXuatBanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.App_Start;
using WebApplication1.Models;
namespace WebApplication1.Areas.Admin.Controllers
{
    public class NhaXuatBanController : Controller
    {
        // GET: Admin/NhaXuatBan
        QLBanSachEntities db = new QLBanSachEntities();
        [AdminAuthorize()]
        public ActionResult Index(int? page)
        {
            const int PageSize = 10;
            int NowPage = page ?? 1;
            List<NHAXUATBAN> s = db.NHAXUATBANs.ToList();
            int ItemTotal = s.Count();
            int SkipPage = (NowPage - 1) * PageSize;
            var pager = new Pager(ItemTotal, NowPage, PageSize);
            List<NHAXUATBAN> s1 = s.OrderBy(item => item.MaNXB).Skip(SkipPage).Take(PageSize).ToList();
            ViewBag.p = pager;
            return View(s1);
        }
        [AdminAuthorize()]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection f)
        {
            var TenNxb = f["sNameNxb"];
            var DiaChi = f["sDiaChi"];
            var DienThoai = f["sDienThoai"];
            NHAXUATBAN nbx = new NHAXUATBAN();

            nbx.TenNXB = TenNxb;
            nbx.DiaChi = DiaChi;
            nbx.DienThoai = DienThoai;
            db.NHAXUATBANs.Add(nbx);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id)
        {
            NHAXUATBAN nbx = db.NHAXUATBANs.FirstOrDefault(item => item.MaNXB==id);
            return View(nbx);
        }
        [HttpPost]
        public ActionResult Edit(FormCollection f)
        {
            int id = int.Parse(f["iMaNXB"]);
            var TenNxb = f["sNameNxb"];
            var DiaChi = f["sDiaChi"];
            var DienThoai = f["sDienThoai"];
            NHAXUATBAN nxb = db.NHAXUATBANs.FirstOrDefault(item => item.MaNXB==id);
            nxb.TenNXB = TenNxb;
            nxb.DiaChi = DiaChi;
            nxb.DienThoai = DienThoai;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            NHAXUATBAN nbx = db.NHAXUATBANs.FirstOrDefault(item => item.MaNXB==id);
            return View(nbx);
        }

        public ActionResult Delete(int id)
        {
            NHAXUATBAN nbx = db.NHAXUATBANs.FirstOrDefault(item => item.MaNXB == id);
            //db.NHAXUATBANs.Remove(nbx);
            return View(nbx);
        }
        [HttpPost]
        public ActionResult Delete(FormCollection f)
        {
            int id = int.Parse(f["iMaNXB"]);
            NHAXUATBAN nbx = db.NHAXUATBANs.FirstOrDefault(item => item.MaNXB == id);
            db.NHAXUATBANs.Remove(nbx);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

sachOnline/WebApplication1/Areas/Admin/Views/NhaXuatBan/Create.cshtml
@model WebApplication1.Models.NHAXUATBAN

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "NhaXuatBan",FormMethod.Post)) 
{
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
        <h4>NHAXUATBAN</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TenNXB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" class="form-control" name="sNameNxb"/>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control" type="text" name="sDiaChi"/>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DienThoai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control" type="text" name="sDienThoai"/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

sachOnline/WebApplication1/Areas/Admin/Views/NhaXuatBan/Delete.cshtml
@model WebApplication1.Models.NHAXUATBAN

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Có chắc muốn xóa không</h3>
<div>
    <h4>NHAXUATBAN</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenNXB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNXB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DienThoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DienThoai)
        </dd>

    </dl>

    <form action="~/Admin/NhaXuatBan/Delete" method="post">
        <input type="hidden" name="iMaNXB" value="@Model.MaNXB" />
        <button class="btn btn-default" type="submit">Xóa</button>
    </form>

    <div class="form-actions no-color">
        @Html.ActionLink("Back to List", "Index")
    </div>
    
</div>

sachOnline/WebApplication1/Areas/Admin/Views/NhaXuatBan/Details.cshtml
@model WebApplication1.Models.NHAXUATBAN

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>NHAXUATBAN</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenNXB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNXB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DienThoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DienThoai)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaNXB }) |
    @Html.ActionLink("Back to List", "Index")
</p>

sachOnline/WebApplication1/Areas/Admin/Views/NhaXuatBan/Edit.cshtml
@model WebApplication1.Models.NHAXUATBAN

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>NHAXUATBAN</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MaNXB)
    <div class="form-group">
        <label class="control-label col-md-2">Mã chủ đề:</label>
        <div class="col-md-10">
            <input type="text" size="70" name="iMaNXB" value="@Model.MaNXB" readonly />
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.TenNXB, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input class="form-control" type="text" name="sNameNXB" value="@Model.TenNXB" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input class="form-control" type="text" name="sDiaChi" value="@Model.DiaChi" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DienThoai, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input class="form-control" type="tel" name="sDienThoai" value="@Model.DienThoai" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

sachOnline/WebApplication1/Areas/Admin/Views/NhaXuatBan/Index.cshtml
@model IEnumerable<WebApplication1.Models.NHAXUATBAN>
@using WebApplication1.Models
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    Pager p = ViewBag.p;
}
@*Xây dựn một helper tùy chỉnh để cắt độ dài chuỗi*@ @helper Truncate(string s, int length)
{
    if (s.Length < length)
    {
        @s
    }
    else
    {
        @s.Substring(0, length)<text>...</text>
    }
}
<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Mã Nhà Xuất Bản
        </th>
        <th>
            Tên Nhà Xuất Bản
        </th>
        <th>
            Địa Chỉ
        </th>
        <th>
            Số Điện Thoại
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.MaNXB
            </td>
            <td>
                @Html.Raw(Truncate(item.TenNXB, 70).ToString())
            </td>
            <td>
                @Html.Raw(Truncate(item.DiaChi, 70).ToString())
            </td>
            <td>
                @item.DienThoai
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.MaNXB }) |
                @Html.ActionLink("Details", "Details", new { id = item.MaNXB }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.MaNXB })
            </td>
        </tr>
    }
</table>

@section MenuPager{
    <div class="container">
        <ul class="pagination justify-content-end">
            @for (int i = p.StartPage; i <= p.EndPage; i++)
            {
                <li class="page-item @(i==p.CurrentPage ? "active" : "")">
                    <a class="page-link" href="~/Admin/NhaXuatBan/Index?page=@i">@i</a>
                </li>
            }
        </ul>
    </div>
}